
---
author: "Clayton T. Lamb"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: github_document
---
```{r render, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE, results='hide'}
rmarkdown::render('temporal_seral_mechs.Rmd',
                  output_file = "README.md")
```

##Load Data, Functions and Cleanup Data
```{r Load Data, message=FALSE, warning=FALSE}
library(raster)
library(sf)
library(mapview)
library(here)
library(lme4)
library(sjPlot)
library(tidyverse)

##load cutblocks
cb<- st_read(here::here("data", "cutblocks", "cutblocks.shp"))

##load dVI
rastlist <- list.files(path = here::here("data",  "dvi_annual_500m"), pattern='.tif', all.files=TRUE, full.names=TRUE)

order <- str_split(list.files(path = here::here("data",  "dvi_annual_500m"), pattern='.tif', all.files=TRUE),
            ".tif", simplify=TRUE)[,1]%>%
    as.numeric()

new.order <- tibble(reord=1:length(order),
       current=order)%>%
  arrange(current)
  
stack <- stack(rastlist[new.order$reord])

##load water mask
water <- raster(here::here("data", "water.tif"))%>%
  projectRaster(stack[[1]])%>%
  is.na()

values(water)[values(water)==0]<-2
values(water)<- values(water)-1
values(water)[is.na(values(water))]<-0
plot(water)

##remove water from dVI
stack<- stack*water


##fix up layers
for(i in 1:nlayers(stack)){
  values(stack[[i]])[values(stack[[i]])<0] <- 1
  values(stack[[i]])[values(stack[[i]])==0]<-NA
}



##rename
names(stack) <- paste0("X", 2000:2020)

##plot
plot(stack)
```

##filter cutblocks to years of interest, and those of appropriate size
```{r filter, message=FALSE, warning=FALSE}
cb.year <-  cb%>%
  filter(HARVEST_YE %in% c(2003:2017))%>%
  mutate(area=st_area(.)%>%as.numeric())%>%
  filter(area>250000)

mean(st_area(cb.year))
quantile(st_area(cb.year), 0.05)
quantile(st_area(cb.year), 0.95)
```
##Map
```{r map, message=FALSE, warning=FALSE}
can <- st_read(here::here("data", "canada", "canada.shp"))%>%
  st_transform(st_crs(cb.year))


plot(st_geometry(cb.year),  border = 'grey', axes = TRUE)
plot(st_geometry(can), pch = 3, col = 'grey', add = TRUE)
plot(st_geometry(cb.year),  border = 'red', axes = TRUE, add = TRUE)
```

##extract dVI to cublocks
```{r extract, results='hide', message=FALSE, warning=FALSE}
a <- raster::extract(stack,as(cb.year,"Spatial"), fun=mean, na.rm=TRUE, method="simple",df=TRUE)
    
df <- cbind(as.data.frame(cb.year),a)%>%
  as.data.frame()%>%
  dplyr::select(-geometry)%>%
  gather(year,dvi,-HARVEST_YE,-ID,-prov)%>%
  mutate(year=str_sub(year,2,5)%>%as.numeric)%>%
  mutate(time=year-HARVEST_YE)
```


##Plot Raw Data
```{r plot, results='hide', message=FALSE, warning=FALSE}
precut <- df%>%
  drop_na(time)%>%
  ungroup()%>%
  filter(time%in%c(-10:-1))%>%
  group_by(ID)%>%
  summarise(baseline=mean(dvi, na.rm=TRUE))
  
contrast <- df%>%
    drop_na(time)%>%
  left_join(precut, by="ID")%>%
  drop_na(baseline)%>%
  ungroup()%>%
  group_by(ID)%>%
  mutate(change=((dvi-baseline)/baseline)*100)%>%
  ungroup()


 contrast%>%
  filter(time>=-10 & time<18)%>%
ggplot(aes(x=time, y=change))+
  geom_vline(xintercept = 0, linetype="dotted")+
  geom_point(col="red", alpha=0.01)+
  theme_bw()+
  xlab("time since cut (years)")+
  ylab("change from pre-cut dVI (%)")+
   facet_grid(.~prov)
 
 
 contrast%>%
   filter(time>=-10 & time<18)%>%
   ggplot(aes(x=time, y=change))+
   geom_vline(xintercept = 0, linetype="dotted")+
   geom_point(col="red", alpha=0.01)+
   theme_bw()+
   xlab("Time since cut (years)")+
   ylab("Change from pre-cut vegetation index (%)")


```

##Test for significant effect post logging
```{r mixed model,  message=FALSE, warning=FALSE}

##prep data
model.data <-
  contrast%>%
  mutate(period=case_when(time<0~"Pre",
                          time>0~"Post"))%>%
  mutate(period=fct_relevel(period, "Pre", "Post"))%>%
  drop_na(period, time)

##run model with dVI values
m1 <- lmer(dvi ~ period + (1|ID), data=model.data)
summary(m1)

##plot model
plot_model(m1,
  sort.est = TRUE,
  title = "",
type="pred",
  axis.title=c("deltaVI"),
ci.lvl=0.95)

model.data%>%
  group_by(period)%>%
  summarise(mean(dvi))

##using the change
m2 <- lmer(change ~ period + (1|ID), data=model.data)
summary(m2)

plot_model(m2,
  sort.est = TRUE,
  title = "",
type="pred",
  axis.title=c(" % change in deltaVI"),
ci.lvl=0.95)
```


##Bootstrap results for a time-specific plot
```{r bootstrap, results='hide', message=FALSE, warning=FALSE}
boot.dat <- data.frame()
for(i in 1:500){
dat <-  contrast%>%
  group_by(ID)%>%
  sample_frac(1,replace = TRUE)%>%
  filter(time>=-10 & time<14)%>%
  drop_na(time,ID,dvi)

mod <- dat%>%
  lmer(dvi ~ as.character(time) + (1|ID), data=.)

dat$pred <-predict(mod)



boot.dat <- dat%>%
  group_by(time)%>%
  summarise(av=mean(dvi,na.rm=TRUE))%>%
  mutate(iter=i)%>%
  rbind(boot.dat)
}



boot.dat%>%
   group_by(time)%>%
   summarise(mean=mean(av, na.rm=TRUE),
             lower=quantile(av, 0.05),
             upper=quantile(av,0.95))%>%
   ggplot(aes(x=time, y=mean))+
   geom_vline(xintercept = 0, linetype="dotted")+
   geom_errorbar(aes(ymin = lower, ymax = upper), width=0.01, alpha=0.2)+
   geom_point(col="red")+
   theme_bw()+
   xlab("Time since cut (years)")+
   ylab("Change from pre-cut vegetation index (%)")


precut.boot <- boot.dat%>%
  ungroup()%>%
  filter(time%in%c(-10:-1))%>%
  group_by(iter)%>%
  summarise(baseline=mean(av, na.rm=TRUE))
  
contrast.boot <- boot.dat%>%
  ungroup()%>%
  left_join(precut.boot, by="iter")%>%
  mutate(change=((av-baseline)/baseline)*100)

  
   contrast.boot%>%
     group_by(time)%>%
   summarise(mean=mean(change, na.rm=TRUE),
             lower=quantile(change, 0.05),
             upper=quantile(change,0.95))%>%
   ggplot(aes(x=time, y=mean))+
   geom_vline(xintercept = 0, linetype="dotted")+
   geom_errorbar(aes(ymin = lower, ymax = upper), width=0.01, alpha=1, color="black")+
   geom_point(col="red")+
   theme_bw()+
   theme(panel.grid.minor = element_blank())+
   xlab("Time since cut (years)")+
   ylab("Change from pre-cut vegetation index (%)")
   
    ggsave(here::here("plots", "time_since_cut_dEVI.png"),width=6, height=4)


```
